// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZacNkB1yuNYRA7t2DP0RYBKPdRk1dx3E',
    appId: '1:39491563305:web:49e1bcb82c2f192729d138',
    messagingSenderId: '39491563305',
    projectId: 'jain-donationapp',
    authDomain: 'jain-donationapp.firebaseapp.com',
    storageBucket: 'jain-donationapp.appspot.com',
    measurementId: 'G-4CWJ7D6W2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vemitTmSujgQ1_e6QMMy8vIm3Io82Fk',
    appId: '1:39491563305:android:bcba57bf8f041c4329d138',
    messagingSenderId: '39491563305',
    projectId: 'jain-donationapp',
    storageBucket: 'jain-donationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MNfjARatum2-XNwvZZP_xEQfFJ-91ps',
    appId: '1:39491563305:ios:9a661c250d6c04d729d138',
    messagingSenderId: '39491563305',
    projectId: 'jain-donationapp',
    storageBucket: 'jain-donationapp.appspot.com',
    iosClientId: '39491563305-ast3ag5bc55gbeu2j9uhog4qhb36g7js.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationsapp',
  );
}
